### ISSUE TITLE
app instantly closes as soon as opened (mac)

### ISSUE THREAD

**Issue by ssjblue-xxx** [Haeri/MonolithCode2#25]
hello, i'm in need of assistance. The app keepy closing after opening it (as said in the title). does anyone knows how to fix?

**Comment by Haeri** [comment]
Hi @ssjblue-xxx 

The master branch has an older electron version which has issues on macOS. Try either switching to the [electron17](https://github.com/Haeri/MonolithCode2/tree/electron17) branch or just download the latest build from that branch from the actions page at the bottom: https://github.com/Haeri/MonolithCode2/actions/runs/2198877970

Best regards,
Haeri

**Comment by ssjblue-xxx** [comment]
ok i'll try (sorry for late response)

**Comment by ssjblue-xxx** [comment]
ok it worked thanks !
